name: Deploy Nomi to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-nomi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Environment Secrets
        env:
          ${{ secrets }}
        run: |
          MISSING_VARS=0
          # Check if DISCORD_API_KEY is populated
          if [ -z "$DISCORD_API_KEY" ]; then
            echo "Error: DISCORD_API_KEY is not set or is empty. Please add it to your repository secrets."
            ((MISSING_VARS++)) ||:
          else
            echo "DISCORD_API_KEY is set."
          fi
          # Check if RENDER_API_KEY is populated
          if [ -z "$RENDER_API_KEY" ]; then
            echo "Error: RENDER_API_KEY is not set or is empty. Please add it to your repository secrets."
            ((MISSING_VARS++)) ||:
          else
            echo "RENDER_API_KEY is set."
          fi
          # Check if NOMI_API_KEY is populated
          if [ -z "$NOMI_API_KEY" ]; then
            echo "Error: NOMI_API_KEY is not set or is empty. Please add it to your repository secrets."
            ((MISSING_VARS++)) ||:
          else
            echo "NOMI_API_KEY is set."
          fi
          # Check if NOMI_ID is populated
          if [ -z "$NOMI_ID" ]; then
            echo "Error: NOMI_ID is not set or is empty. Please add it to your repository secrets."
            ((MISSING_VARS++)) ||:
          else
            echo "NOMI_ID is set."
          fi
          exit $MISSING_VARS

      - name: Validate API Keys
        env:
          ${{ secrets }}
        run: |
          INVALID_API_KEYS=0
          # Check Render API key is valid
          RESPONSE=$(curl -s -w "%{http_code}" \
            --request GET \
            --header "Authorization: Bearer $RENDER_API_KEY" \
            --header "Accept: application/json" \
            --url "https://api.render.com/v1/services?limit=1")
          HTTP_STATUS="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE::-3}"
          if [ "$HTTP_STATUS" -eq 401 ]; then
            echo "Error: Invalid Render API Key. Authentication failed."
            ((INVALID_API_KEYS++)) ||:
          elif [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to validate Render API Key. HTTP Status: $HTTP_STATUS"
            exit 1
          else
            echo "Render API Key is valid."
          fi

          # Check Nomi API key is valid
          RESPONSE=$(curl -s -w "%{http_code}" \
            --request GET \
            --header "Authorization: $NOMI_API_KEY" \
            --header "Accept: application/json" \
            --url "https://api.nomi.ai/v1/nomis")
          HTTP_STATUS="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE::-3}"
          if [ "$HTTP_STATUS" -eq 400 ]; then
            echo "Error: Invalid Nomi API Key. Authentication failed."
            ((INVALID_API_KEYS++)) ||:
          elif [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to validate Nomi API Key. HTTP Status: $HTTP_STATUS"
            exit 1
          else
            echo "Nomi API Key is valid."
          fi

          # Check Discord API key is valid
          RESPONSE=$(curl -s -w "%{http_code}" \
            --request GET \
            --header "Authorization: Bot $DISCORD_API_KEY" \
            --header "Accept: application/json" \
            --url "https://discord.com/api/v10/users/@me")
          HTTP_STATUS="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE::-3}"
          if [ "$HTTP_STATUS" -eq 400 ]; then
            echo "Error: Invalid Discord API Key. Authentication failed."
            ((INVALID_API_KEYS++)) ||:
          elif [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to validate Discord API Key. HTTP Status: $HTTP_STATUS"
            exit 1
          else
            echo "Discord API Key is valid."
          fi
          exit $INVALID_API_KEYS

      - name: Get Nomi Name from Nomi API
        id: get-nomi-name
        env:
          NOMI_API_KEY: ${{ secrets.NOMI_API_KEY }}
          NOMI_ID: ${{ secrets.NOMI_ID }}
        run: |
          # Get Nomi name from Nomi ID
          RESPONSE=$(curl -s -w "%{http_code}" \
            --request GET \
            --header "Authorization: $NOMI_API_KEY" \
            --header "Accept: application/json" \
            --url "https://api.nomi.ai/v1/nomis/$NOMI_ID")
          HTTP_STATUS="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE::-3}"
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to retrieve Nomi Name from Nomi API. HTTP Status: $HTTP_STATUS"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi
          # Parse the Nomi Name from the response
          NOMI_NAME=$(echo "$RESPONSE_BODY" | jq -r '.name')
          if [ -z "$NOMI_NAME" ] || [ "$NOMI_NAME" == "null" ]; then
            echo "Error: Nomi Name not found in the API response."
            exit 1
          fi
          echo "Successfully retrieved Nomi Name: $NOMI_NAME"
          echo "NOMI_NAME=$NOMI_NAME" >> $GITHUB_OUTPUT

      - name: Normalize Nomi Name
        id: get-normalized-nomi-name
        env:
          NOMI_NAME: ${{ steps.get-nomi-name.outputs.NOMI_NAME }}
        run: |
          if [ -z "$NOMI_NAME" ]; then
            echo "Error: NOMI_NAME is empty."
            exit 1
          fi
          NORMALIZED_NOMI_NAME=$(echo -n "$NOMI_NAME" | iconv -f utf-8 -t ascii//TRANSLIT | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9.-' '_')
          if [ -z "$NORMALIZED_NOMI_NAME" ]; then
            echo "Error: Normalized Nomi Name is empty."
            exit 1
          fi
          echo "Normalized Nomi Name: $NORMALIZED_NOMI_NAME"
          echo "NORMALIZED_NOMI_NAME=$NORMALIZED_NOMI_NAME" >> $GITHUB_OUTPUT

      - name: Get Service Name from render.yaml
        id: get-service-name
        run: |
          SERVICE_NAME=$(grep '^\s*name:' render.yaml | sed 's/.*name: *//')
          if [ -z "$SERVICE_NAME" ]; then
            echo "Error: Could not find 'name:' field in render.yaml."
            exit 1
          fi
          echo "Service name: $SERVICE_NAME"
            echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_OUTPUT

      - name: Check for Existing Blueprint
        id: check-existing-blueprint
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_NAME: ${{ steps.get-service-name.outputs.SERVICE_NAME }}
        run: |
          # Fetch existing blueprints
          RESPONSE=$(curl -s -w "%{http_code}" \
            --request GET \
            --header "Authorization: Bearer $RENDER_API_KEY" \
            --header "Accept: application/json" \
            --url "https://api.render.com/v1/blueprints")
          HTTP_STATUS="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE::-3}"
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to retrieve blueprints. HTTP Status: $HTTP_STATUS"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi

          # Check if the response is a valid JSON array
          IS_ARRAY=$(echo "$RESPONSE_BODY" | jq 'type == "array"')
          if [ "$IS_ARRAY" != "true" ]; then
            echo "Error: Expected an array in the response."
            exit 1
          fi

          # Check if any blueprints exist
          BLUEPRINT_COUNT=$(echo "$RESPONSE_BODY" | jq 'length')
          if [ "$BLUEPRINT_COUNT" -eq 0 ]; then
            echo "No existing blueprints found. Please add a blueprint."
            exit 1
          fi

          EXISTING_BLUEPRINT=$(echo "$RESPONSE_BODY" | jq -c --arg NAME "$SERVICE_NAME" '.[] | select(.blueprint.name == $NAME)')
          echo "$EXISTING_BLUEPRINT"
          if [ -z "$EXISTING_BLUEPRINT" ]; then
            echo "No existing blueprints with the name $SERVICE_NAME were found."
            exit 1
          else
            echo "An existing blueprint with the name $SERVICE_NAME was found."
          fi

      - name: Check for Existing Generic Service
        id: check-existing-service
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_NAME: ${{ steps.get-service-name.outputs.SERVICE_NAME }}
        continue-on-error: true
        run: |
          # Fetch existing services
          RESPONSE=$(curl -s -w "%{http_code}" \
            --request GET \
            --header "Authorization: Bearer $RENDER_API_KEY" \
            --header "Accept: application/json" \
            --url "https://api.render.com/v1/services?includePreviews=true&limit=50")
          HTTP_STATUS="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE::-3}"
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to retrieve services. HTTP Status: $HTTP_STATUS"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi

          # Check if the response is a valid JSON array
          IS_ARRAY=$(echo "$RESPONSE_BODY" | jq 'type == "array"')
          if [ "$IS_ARRAY" != "true" ]; then
            echo "Error: Expected an array in the response."
            exit 1
          fi

          # Check if any blueprints exist
          BLUEPRINT_COUNT=$(echo "$RESPONSE_BODY" | jq 'length')
          if [ "$BLUEPRINT_COUNT" -eq 0 ]; then
            echo "No existing services found."
            exit 1
          fi

          EXISTING_SERVICE=$(echo "$RESPONSE_BODY" | jq -r --arg NAME "$SERVICE_NAME" '.[] | select(.service.name == $NAME) | .service')
          if [ -n "$EXISTING_SERVICE" ] && [ "$EXISTING_SERVICE" != "null" ]; then
            echo "An existing service with the name $SERVICE_NAME was found."
            SERVICE_ID=$(echo "$EXISTING_SERVICE" | jq -r '.id')
            echo "SERVICE_ID=$SERVICE_ID" >> $GITHUB_OUTPUT
          else
            echo "No existing services the name $SERVICE_NAME were found."
            exit 1
          fi

      - name: Rename Service to match our Nomi's Name
        if: steps.check-existing-service.outcome == 'success'
        id: rename-generic-service
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ steps.check-existing-service.outputs.SERVICE_ID }}
          NOMI_NAME: ${{ steps.get-normalized-nomi-name.outputs.NORMALIZED_NOMI_NAME }}
        run: |
          # Ensure the value is properly escaped for JSON
          NAME_ESCAPED=$(printf '%s' "$NOMI_NAME" | jq -Rs '.')
          # Fetch existing services
          RESPONSE=$(curl -s -w "%{http_code}" \
            --request GET \
            --header "Authorization: Bearer $RENDER_API_KEY" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data "{\"name\":$NAME_ESCAPED}" \
            --url "https://api.render.com/v1/services/$SERVICE_ID")
          HTTP_STATUS="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE::-3}"
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to rename Service. HTTP Status: $HTTP_STATUS"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi

      # This is a sanity check more than anything. Here,
      # We just make sure that a service corresponding
      # to our nomi's name exists
      - name: Check Existing Named Service
        id: check-existing-named-service
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          NOMI_NAME: ${{ steps.get-normalized-nomi-name.outputs.NORMALIZED_NOMI_NAME }}
        run: |
          # Fetch existing services
          RESPONSE=$(curl -s -w "%{http_code}" \
            --request GET \
            --header "Authorization: Bearer $RENDER_API_KEY" \
            --header "Accept: application/json" \
            --url "https://api.render.com/v1/services?includePreviews=true&limit=50")
          HTTP_STATUS="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE::-3}"
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to retrieve services. HTTP Status: $HTTP_STATUS"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi

          # Check if the response is a valid JSON array
          IS_ARRAY=$(echo "$RESPONSE_BODY" | jq 'type == "array"')
          if [ "$IS_ARRAY" != "true" ]; then
            echo "Error: Expected an array in the response."
            exit 1
          fi

          # Check if any blueprints exist
          BLUEPRINT_COUNT=$(echo "$RESPONSE_BODY" | jq 'length')
          if [ "$BLUEPRINT_COUNT" -eq 0 ]; then
            echo "No existing services found."
            exit 1
          fi

          EXISTING_SERVICE=$(echo "$RESPONSE_BODY" | jq -r --arg NAME "$NOMI_NAME" '.[] | select(.service.name == $NAME) | .service')
          if [ -n "$EXISTING_SERVICE" ] && [ "$EXISTING_SERVICE" != "null" ]; then
            echo "An existing service with the name $NOMI_NAME was found."
            ENV_GROUP_ID=$(echo "$EXISTING_SERVICE" | jq -r '.id')
            echo "EXISTING_SERVICE=$ENV_GROUP_ID" >> $GITHUB_OUTPUT
          else
            echo "No existing service the name $NOMI_NAME was found."
            exit 1
          fi

      - name: Check for Existing Environment Group
        id: check-existing-env-group
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_NAME: ${{ steps.get-service-name.outputs.SERVICE_NAME }}
        run: |
          # Fetch existing environment groups
          RESPONSE=$(curl -s -w "%{http_code}" \
            --request GET \
            --header "Authorization: Bearer $RENDER_API_KEY" \
            --header "Accept: application/json" \
            --url "https://api.render.com/v1/env-groups")
          HTTP_STATUS="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE::-3}"
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to retrieve environment groups. HTTP Status: $HTTP_STATUS"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi

          # Check if the response is a valid JSON array
          IS_ARRAY=$(echo "$RESPONSE_BODY" | jq 'type == "array"')
          if [ "$IS_ARRAY" != "true" ]; then
            echo "Error: Expected an array in the response."
            exit 1
          fi

          # Check if any environment groups exist
          ENV_GROUP_COUNT=$(echo "$RESPONSE_BODY" | jq 'length')
          if [ "$ENV_GROUP_COUNT" -eq 0 ]; then
            echo "No existing environment groups found."
            exit 1
          fi

          # Ensure an environment group that matches our app
          EXISTING_GROUP=$(echo "$RESPONSE_BODY" | jq -r --arg NAME "$SERVICE_NAME" '.[] | select(.envGroup.name == $NAME) | .envGroup')
          if [ -n "$EXISTING_GROUP" ] && [ "$EXISTING_GROUP" != "null" ]; then
            echo "An existing environment group with the name $SERVICE_NAME was found."
            ENV_GROUP_ID=$(echo "$EXISTING_GROUP" | jq -r '.id')
            echo "EXISTING_GROUP_ID=$ENV_GROUP_ID" >> $GITHUB_OUTPUT
            echo "EXISTING_GROUP=true" >> $GITHUB_OUTPUT
          else
            echo "No existing environment groups with the name $SERVICE_NAME were found."
            exit 1
          fi

      - name: Update Environment Variables from GitHub Secrets and nomi.conf
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          ENV_GROUP_ID: ${{ steps.check-existing-env-group.outputs.EXISTING_GROUP_ID }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          # Read nomi.conf file and convert to JSON object
          CONF_JSON="{}"
          if [ -f setup/nomi.conf ]; then
            while IFS='=' read -r KEY VALUE; do
              # Skip lines that are empty or start with a comment
              if [[ -z "$KEY" || "$KEY" =~ ^# ]]; then
                continue
              fi
              KEY=$(echo "$KEY" | xargs)
              VALUE=$(echo "$VALUE" | xargs)
              # Add key-value pair to CONF_JSON using jq
              CONF_JSON=$(echo "$CONF_JSON" | jq --arg KEY "$KEY" --arg VALUE "$VALUE" '.[$KEY] = $VALUE')
            done < setup/nomi.conf
          else
            echo "The file 'nomi.conf' was not found"
            exit 1
          fi

          # Merge nomi.conf values first, then let secrets override them
          ALL_ENV_VARS=$(echo "$CONF_JSON" | jq --argjson secrets "$SECRETS" '. * $secrets')
          ENV_VAR_KEYS=$(echo "$ALL_ENV_VARS" | jq -r 'keys[]')

          for KEY in $ENV_VAR_KEYS; do
            if [[ $KEY == "github_token" || $KEY == "RENDER_API_KEY" ]]; then
              continue
            fi
            # URL-encode the KEY
            ENCODED_KEY=$(printf '%s' "$KEY" | jq -sRr @uri)

            # Ensure the value is properly escaped for JSON
            VALUE=$(echo "$ALL_ENV_VARS" | jq -r --arg KEY "$KEY" '.[$KEY]')
            VALUE_ESCAPED=$(printf '%s' "$VALUE" | jq -Rs '.')

            RESPONSE=$(curl -s -w "%{http_code}" \
              --request PUT \
              --header "Authorization: Bearer $RENDER_API_KEY" \
              --header "Accept: application/json" \
              --header "Content-Type: application/json" \
              --data "{\"value\":$VALUE_ESCAPED}" \
              --url "https://api.render.com/v1/env-groups/$ENV_GROUP_ID/env-vars/$ENCODED_KEY")
            HTTP_STATUS="${RESPONSE: -3}"
            RESPONSE_BODY="${RESPONSE::-3}"
            if [ "$HTTP_STATUS" -ne 200 ]; then
              echo "Error: Failed to update env var $KEY. HTTP Status: $HTTP_STATUS"
              echo "Response: $RESPONSE_BODY"
              exit 1
            fi
            echo "Successfully updated env var $KEY."
          done

      - name: Inform Nomi Container it is running on Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          ENV_GROUP_ID: ${{ steps.check-existing-env-group.outputs.EXISTING_GROUP_ID }}
        run: |
          KEY="ON_RENDER"
          VALUE="True"

          ENCODED_KEY=$(printf '%s' "$KEY" | jq -sRr @uri)
          VALUE_ESCAPED=$(printf '%s' "$VALUE" | jq -Rs '.')

          RESPONSE=$(curl -s -w "%{http_code}" \
            --request PUT \
            --header "Authorization: Bearer $RENDER_API_KEY" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data "{\"value\":$VALUE_ESCAPED}" \
            --url "https://api.render.com/v1/env-groups/$ENV_GROUP_ID/env-vars/$ENCODED_KEY")
          HTTP_STATUS="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE::-3}"
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to update env var $KEY. HTTP Status: $HTTP_STATUS"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi
          echo "Successfully updated env var $KEY."
